# Generated by Django 5.0.1 on 2026-05-27 18:55

import django.db.models.deletion
import django.utils.timezone
import propylon_document_manager.file_versions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fileversion",
            options={"ordering": ["file_url", "version_number"]},
        ),
        migrations.AddField(
            model_name="fileversion",
            name="content_type",
            field=models.CharField(blank=True, default="application/octet-stream", max_length=255),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fileversion",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=propylon_document_manager.file_versions.models.file_upload_path
            ),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="file_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="file_size",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="file_url",
            field=models.CharField(db_index=True, default="", max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fileversion",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_versions",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="fileversion",
            unique_together={("owner", "file_url", "version_number")},
        ),
    ]
