# Generated by Django 5.0.1 on 2026-05-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_alter_fileversion_options_fileversion_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="read_permission",
            field=models.CharField(
                choices=[("private", "Private"), ("public", "Public")], default="private", max_length=10
            ),
        ),
    ]
